FROM ubuntu:14.04
MAINTAINER amumu "moz_han@126.com"
ENV REFRESHED_AT 2019-08-13

RUN apt-get -yqq update && apt-get -yqq install redis-server redis-tools
EXPOSE 6369
ENTRYPOINT ["/usr/bin/redis-server"]
CMD []
