FROM ubuntu:14.04
MAINTAINER amumu "moz_han@126.com"
ENV REFRESHEC_AT 2019-08-11
RUN apt-get -yqq update && apt-get -yqq install nginx
RUN mkdir -p /var/www/html/website
ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/global.conf /etc/nginx/conf.d/
EXPOSE 80
